# Generated by Django 4.1.3 on 2023-03-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BBFinanceStory",
            fields=[
                ("abstract", models.JSONField()),
                ("ad_params", models.JSONField()),
                ("archived", models.BooleanField(default=False)),
                ("attributor", models.CharField(default="", max_length=255)),
                ("authored_region", models.CharField(default="", max_length=255)),
                ("brand", models.CharField(default="", max_length=255)),
                ("byline", models.CharField(default="", max_length=255)),
                ("card", models.CharField(default="", max_length=255)),
                ("components", models.JSONField(default=dict)),
                ("content_tags", models.JSONField(default=dict)),
                ("disable_ads", models.BooleanField(default=False)),
                ("follow_author_details", models.JSONField(default=dict)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("internal_id", models.CharField(default="", max_length=255)),
                ("is_metered", models.BooleanField(default=False)),
                ("lede_image", models.JSONField(default=dict)),
                ("lede_video", models.JSONField(default=dict)),
                ("long_url", models.TextField(default="")),
                ("newsletter_tout_label", models.CharField(default="", max_length=255)),
                ("premium", models.BooleanField(default=False)),
                ("primary_category", models.CharField(default="", max_length=255)),
                ("primary_site", models.CharField(default="", max_length=255)),
                ("published", models.IntegerField(default=0)),
                ("readings", models.JSONField(default=dict)),
                ("resource_id", models.CharField(default="", max_length=255)),
                ("resource_type", models.CharField(default="", max_length=255)),
                ("secondary_brands", models.JSONField(default=dict)),
                ("security_i_ds", models.JSONField(default=dict)),
                ("short_url", models.CharField(default="", max_length=255)),
                ("summary", models.TextField(blank=True, default="")),
                ("themed_images", models.JSONField(default=dict)),
                ("title", models.CharField(default="", max_length=255)),
                ("topics", models.JSONField(default=dict)),
                ("type", models.CharField(default="", max_length=255)),
                ("updated_at", models.IntegerField(default=0)),
                ("word_count", models.IntegerField(default=0)),
                ("ai_summary", models.TextField(blank=True, default="")),
                ("created_at", models.IntegerField(default=1680268354.365322)),
                ("status", models.IntegerField(default=0)),
            ],
        ),
    ]
