# Generated by Django 4.1.3 on 2023-04-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_finance_api', '0004_alter_bbfinancestory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbfinancestory',
            name='created_at',
            field=models.IntegerField(default=1680340452.550786),
        ),
    ]
