# Generated by Django 4.1.3 on 2023-04-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_finance_api', '0006_remove_bbfinancestory_disable_ads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbfinancestory',
            name='disable_ads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bbfinancestory',
            name='primary_category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bbfinancestory',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bbfinancestory',
            name='created_at',
            field=models.IntegerField(default=1680344146.114501),
        ),
    ]
