# Generated by Django 4.1.3 on 2023-04-16 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb_finance_api', '0008_alter_bbfinancestory_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorMetadata',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('protected', models.BooleanField()),
                ('verified', models.BooleanField()),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('public_metrics', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='bbfinancestory',
            name='created_at',
            field=models.IntegerField(default=1681672570.827973),
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('created_at', models.DateTimeField()),
                ('edit_history_tweet_ids', models.JSONField()),
                ('entities', models.JSONField()),
                ('tweet_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb_finance_api.authormetadata')),
            ],
        ),
    ]
