# Generated by Django 4.1.3 on 2023-04-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_finance_api', '0009_authormetadata_alter_bbfinancestory_created_at_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbfinancestory',
            name='created_at',
            field=models.IntegerField(default=1681677257.867413),
        ),
    ]
