# Generated by Django 4.1.3 on 2023-05-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_finance_api', '0010_alter_bbfinancestory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_type',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='bbfinancestory',
            name='created_at',
            field=models.IntegerField(default=1684054845.091297),
        ),
    ]
