version: '3'
services:
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
        #- app_data:/data  # 新的卷
      - shared_data:/data
    ports:
      - "5000:80"
    depends_on:
      - mysql_db
      - redis
      - mongo_db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_HOST: mysql_db
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongo_db
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  mysql_db:
    image: mysql:8.0
    environment:
      # MYSQL_HOST: mysql_db
      # MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo_db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '15672:15672'
      - '5672:5672'


volumes:
  mysql_data:
  redis_data:
  mongo_data:
  #app_data:  # 新的卷
  shared_data:

networks:
  default:
    name: mynetwork
    external: true