# Generated by Django 4.1.3 on 2023-03-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bb_finance_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bbfinancestory",
            name="created_at",
            field=models.IntegerField(default=1680268558.522899),
        ),
    ]
