# Generated by Django 4.1.3 on 2023-04-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_finance_api', '0002_alter_bbfinancestory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbfinancestory',
            name='auto_generated_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bbfinancestory',
            name='created_at',
            field=models.IntegerField(default=1680338946.122497),
        ),
    ]
