# Generated by Django 4.1.3 on 2023-04-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_finance_api', '0003_bbfinancestory_auto_generated_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbfinancestory',
            name='created_at',
            field=models.IntegerField(default=1680340333.723038),
        ),
    ]
