# Generated by Django 4.1.3 on 2023-04-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_finance_api', '0005_alter_bbfinancestory_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbfinancestory',
            name='disable_ads',
        ),
        migrations.RemoveField(
            model_name='bbfinancestory',
            name='primary_category',
        ),
        migrations.RemoveField(
            model_name='bbfinancestory',
            name='word_count',
        ),
        migrations.AlterField(
            model_name='bbfinancestory',
            name='created_at',
            field=models.IntegerField(default=1680344050.784154),
        ),
    ]
